set shell := ["bash", "-c"]
set dotenv-load := true

PROJECT_USER   := "mcooney"
PROJECT_NAME   := "catmodel_elt_documents"
PROJECT_TAG    := "latest"
IMAGE_TAG      := PROJECT_USER + "/" + PROJECT_NAME + ":" + PROJECT_TAG
CONTAINER_NAME := "catmodel-elt-docs"
PWD            := `pwd`

OCI := `command -v podman >/dev/null 2>&1 && echo podman || echo docker`
OCI_FLAGS := if OCI == "podman" { "--userns=keep-id" } else { "" }
MOUNT_SUFFIX := if OCI == "podman" { ":z" } else { "" }

default:
  @just --list

image-build:
  {{OCI}} build -t {{IMAGE_TAG}} \
    --build-arg BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` \
    -f Dockerfile .

image-rebuild:
  {{OCI}} build --no-cache -t {{IMAGE_TAG}} \
    --build-arg BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` \
    -f Dockerfile .

render-dev:
  MODE=dev ./scripts/render_all.sh

render-full:
  MODE=full ./scripts/render_all.sh

render-dev-container:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{PWD}}/..:/repo{{MOUNT_SUFFIX}}" \
    -w /repo/catmodel_elt_documents \
    {{IMAGE_TAG}} \
    bash -lc "MODE=dev ./scripts/render_all.sh"

render-full-container:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{PWD}}/..:/repo{{MOUNT_SUFFIX}}" \
    -w /repo/catmodel_elt_documents \
    {{IMAGE_TAG}} \
    bash -lc "MODE=full ./scripts/render_all.sh"

render-primer-container mode="full":
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{PWD}}/..:/repo{{MOUNT_SUFFIX}}" \
    -w /repo/catmodel_elt_documents \
    {{IMAGE_TAG}} \
    bash -lc "MODE={{mode}} ./scripts/render_primer.sh"

render-quickstart-container:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{PWD}}/..:/repo{{MOUNT_SUFFIX}}" \
    -w /repo/catmodel_elt_documents \
    {{IMAGE_TAG}} \
    bash -lc "./scripts/render_quickstart.sh"

render-index-container:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{PWD}}/..:/repo{{MOUNT_SUFFIX}}" \
    -w /repo/catmodel_elt_documents \
    {{IMAGE_TAG}} \
    bash -lc "./scripts/render_index.sh"

clean:
  rm -rf outputs/

info:
  @echo "OCI: {{OCI}}"
  @echo "Image: {{IMAGE_TAG}}"
  @echo "Project dir: {{PWD}}"
